# Generated by Django 4.0.2 on 2022-02-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название страницы')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'профиль участника',
                'verbose_name_plural': 'профили участников',
            },
        ),
    ]
